# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c68ce797b7d6661cfc5887986ef727e7c66ed80b72bb81176cd4eb9229fb668077cf92fd4417af688a49682c7550a278ff5ba11142d8baec7527ac42232dfdc7

test:
  secret_key_base: 228c6fba5ff3995486c935fa937f0c49438427d84dd0cb67b1ec9e0d5caa15d16de942cbd616ebd74b2582be363f30dde0473dc7e23a4e3b1f616128344affa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
